
const copy={uk:{help:'Довідка',eyebrow:'Перші покупки разом',hero:'Один список.<br>Для вас обох.',intro:'Від першого запуску до спільних покупок — шість коротких кроків.',creator:'Я створюю список',invited:'Мене запросили',guide:'ЖЕНЯ купи продукти',step:'КРОК',back:'← Назад',next:'Наступний крок →',again:'На початок ↺',preview:'Ілюстровані приклади на демонстраційних даних. Довідка в чаті: /help. Повідомити про проблему: /support.',mock:'Макет скрина Telegram · демодані',steps:[
['Мова','Почніть із мови','Відкрийте бот і натисніть Start / «Розпочати». Оберіть українську або English.','Мову можна змінити пізніше: /language.','<div class="bubble">Оберіть мову / Choose your language</div><div class="fakebutton target">🇺🇦 Українська</div><div class="fakebutton">🇬🇧 English</div>'],
['Сім’я','Створіть сім’ю','Натисніть «Створити сім’ю». Потім відкрийте «Сім’я» та запросіть близьку людину.','Створена сім’я ще не означає, що інша людина приєдналася.','<div class="bubble">Ваш спільний список починається зі сім’ї.</div><div class="fakebutton target">Створити сім’ю</div><div class="fakebutton">Приєднатися</div>'],
['Запрошення','Надішліть запрошення','У «Сім’я» натисніть «Запросити учасника». Надішліть посилання партнеру або партнерці.','Людина має відкрити посилання й підтвердити приєднання. Один учасник = список поки бачите лише ви.','<div class="bubble">👥 Сім’я · 1<br>Учасник: ви</div><div class="fakebutton target">Запросити учасника</div><div class="bubble">Після прийняття: 👥 Сім’я · 2 ✓</div>'],
['Додавання','Скажіть, що купити','Надішліть боту текст або голосове: «Молоко, яйця, хліб». Перевірте чернетку й підтвердьте додавання.','Якщо бот почув не те — виправте чернетку до підтвердження. У Mini App товари також можна додати кнопкою +.','<div class="bubble" class="sample-app">🎙 Молоко, яйця, хліб</div><div class="bubble">Молоко<br>Яйця<br>Хліб</div><div class="fakebutton target">✅ Додати</div>'],
['У магазині','Відкрийте список покупок','У боті натисніть «Покупки». Відкриється Mini App: там натискайте галочки біля куплених товарів.','Товар зникне з активного списку для всіх учасників. Фото й нотатки залишаться в каталозі.','<div class="bubble">👥 Сім’я · 2</div><div class="fakebutton target">Покупки</div><div class="bubble">Далі в Mini App: ✓ Молоко</div><div class="bubble">Залишилось купити: яйця, хліб</div>'],
['Фото й допомога','Усе потрібне — під рукою','Для фото надішліть боту зображення упаковки з назвою товару в підписі. Нотатку змініть у картці товару.','Щось не працює? /support → опишіть проблему → «Надіслати». Збережіть номер звернення.','<div class="bubble">📷 Фото упаковки<br>Підпис: «Молоко»</div><div class="fakebutton">Нотатка у картці Mini App</div><div class="fakebutton target">🐞 Повідомити про проблему</div>']
],join:[['Сім’я','Відкрийте запрошення','Попросіть близьку людину надіслати запрошення з розділу «Сім’я». Відкрийте її посилання в Telegram.','Щоб мати спільний список, приєднайтеся до її сім’ї. Другу сім’ю створювати не потрібно.','<div class="bubble">Запрошення до спільного списку<br>t.me/…?start=invite_…</div><div class="fakebutton target">Відкрити посилання</div>'],['Приєднання','Підтвердьте приєднання','Перевірте, хто вас запросив. Натисніть «Приєднатися». Після цього в розділі «Сім’я» мають бути ви обоє.','Якщо у вас уже є своя сім’я, бот запропонує перехід. «Перенести список» переносить активні покупки; каталог та історія не переносяться.','<div class="bubble">Юлія запрошує до «Наші покупки».</div><div class="fakebutton target">Приєднатися</div><div class="bubble">Перевірте: 👥 Сім’я · 2 ✓</div>']]},
en:{help:'Help',eyebrow:'Your first shared shop',hero:'One list.<br>For both of you.',intro:'From opening the bot to shopping together — six short steps.',creator:'I’m creating a list',invited:'I’ve been invited',guide:'ZHENYA · shopping bot',step:'STEP',back:'← Back',next:'Next step →',again:'Start again ↺',preview:'Illustrated examples with sample data. Chat help: /help. Report a problem: /support.',mock:'Telegram screenshot mockup · sample data',steps:[
['Language','Choose your language','Open the bot and tap Start. Choose Ukrainian or English.','You can change it later with /language.','<div class="bubble">Оберіть мову / Choose your language</div><div class="fakebutton">🇺🇦 Українська</div><div class="fakebutton target">🇬🇧 English</div>'],
['Family','Create a family','Tap “Create family”. Then open “Family” to invite someone.','Creating a family does not automatically add another person.','<div class="bubble">A shared list starts with a family.</div><div class="fakebutton target">Create family</div><div class="fakebutton">Join</div>'],
['Invitation','Share your invitation','In “Family”, tap “Invite a member”. Send the link to your partner.','They must open the link and confirm joining. With one member, only you can see this list.','<div class="bubble">👥 Family · 1<br>Member: you</div><div class="fakebutton target">Invite a member</div><div class="bubble">After they join: 👥 Family · 2 ✓</div>'],
['Add items','Say what you need','Send a text or voice message: “Milk, eggs, bread”. Review the draft and confirm adding it.','If the bot misheard you, edit the draft before confirming. You can also add items with + in the Mini App.','<div class="bubble" class="sample-app">🎙 Milk, eggs, bread</div><div class="bubble">Milk<br>Eggs<br>Bread</div><div class="fakebutton target">✅ Add</div>'],
['Shopping','Open your shopping list','Tap “Shopping” in the bot. It opens the Mini App, where you can tick off items you bought.','It leaves the active list for every family member. Its photo and notes remain in the catalog.','<div class="bubble">👥 Family · 2</div><div class="fakebutton target">Shopping</div><div class="bubble">Then in the Mini App: ✓ Milk</div><div class="bubble">Still to buy: eggs, bread</div>'],
['Photos & help','Keep the details handy','Send the bot a package photo with the product name in its caption. Edit notes in the product card.','Something broken? /support → describe the problem → “Send”. Keep your report number.','<div class="bubble">📷 Package photo<br>Caption: “Milk”</div><div class="fakebutton">Note in the Mini App product card</div><div class="fakebutton target">🐞 Report a problem</div>']
],join:[['Family','Open your invitation','Ask the other person to share an invitation from “Family”. Open their link in Telegram.','Join their family to share a list. You do not need to create a second family.','<div class="bubble">Invitation to a shared list<br>t.me/…?start=invite_…</div><div class="fakebutton target">Open link</div>'],['Joining','Confirm you want to join','Check who invited you. Tap “Join”. Then open “Family” and check that both of you appear.','If you already have a family, the bot offers a switch. Transferring your list moves active items; your catalog and history do not transfer.','<div class="bubble">Julia invites you to “Our shopping”.</div><div class="fakebutton target">Join</div><div class="bubble">Check: 👥 Family · 2 ✓</div>']]}};
let lang=new URLSearchParams(location.search).get('lang')==='en'?'en':'uk',role='creator',step=0;const $=id=>document.getElementById(id);function render(){const c=copy[lang],list=c.steps.map((s,i)=>role==='invited'&&i>0&&i<3?c.join[i-1]:s),s=list[step];document.documentElement.lang=lang;document.body.classList.toggle('has-advanced',step>0);['uk','en'].forEach(k=>$(k).setAttribute('aria-pressed',String(k===lang)));['creator','invited'].forEach(k=>{$(k).textContent=c[k];$(k).setAttribute('aria-pressed',String(k===role))});$('brand-help').textContent=c.help;$('eyebrow').textContent=c.eyebrow;$('hero').innerHTML=c.hero;$('intro').textContent=c.intro;$('guide-label').textContent=c.guide;$('counter').textContent=(step+1)+' / 6';$('kicker').textContent=c.step+' '+(step+1);$('title').textContent=s[1];$('explain').textContent=s[2];$('mock').innerHTML='<div class="caption">'+c.mock+'</div><div class="tg-status"><span>14:32</span><span>●●● ▰</span></div><div class="tg-chathead"><span class="tg-back">‹</span><span class="tg-avatar">Ж</span><div><strong>ЖЕНЯ купи продукти</strong><small>'+(lang==='uk'?'бот':'bot')+'</small></div><span class="tg-dots">⋮</span></div><div class="tg-day">'+(lang==='uk'?'Сьогодні':'Today')+'</div><div class="tg-conversation">'+s[4]+'</div><div class="tg-input"><span>☷</span><span>'+(lang==='uk'?'Повідомлення':'Message')+'</span><span>♧　🎙</span></div>';$('tip').textContent=s[3];$('progress').innerHTML=list.map((_,i)=>'<span class="'+(i<=step?'done':'')+'"></span>').join('');$('steps').innerHTML=list.map((s,i)=>'<button class="step '+(i===step?'active':'')+'" data-step="'+i+'" aria-current="'+(i===step?'step':'false')+'"><span class="number">'+(i+1)+'</span>'+s[0]+'</button>').join('');document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{step=Number(b.dataset.step);render()});$('back').textContent=c.back;$('back').disabled=step===0;$('back').style.opacity=step===0?'.35':'1';$('next').textContent=step===5?c.again:c.next;$('preview').textContent=c.preview}['uk','en'].forEach(l=>$(l).onclick=()=>{lang=l;render()});['creator','invited'].forEach(r=>$(r).onclick=()=>{role=r;render()});$('next').onclick=()=>{step=(step+1)%6;render()};$('back').onclick=()=>{step=Math.max(0,step-1);render()};render();
