#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
cd "$(dirname "$0")/.."
ENV_FILE=.oracle-setup.env

banner "Oracle Always Free — сімейний бот покупок"

stage "Акаунт Oracle Cloud"
open_url "https://signup.oraclecloud.com/"
step "Створіть акаунт Free Tier або увійдіть у наявний. Oracle може попросити телефон і картку для перевірки."
step "Уважно виберіть Home Region: безкоштовну VM можна створити лише там, а регіон потім не змінюється."
step "Не переходьте на платний план. Дочекайтеся листа, що акаунт готовий."
pause "Коли увійшли в Oracle Cloud Console, натисніть Enter."

stage "SSH-ключ для сервера"
SSH_KEY="$HOME/.ssh/family-shopping-oracle"
mkdir -p "$HOME/.ssh"
chmod 700 "$HOME/.ssh"
if [[ ! -f "$SSH_KEY" || ! -f "$SSH_KEY.pub" ]]; then
  step "Створюємо окремий SSH-ключ. За бажанням задайте парольну фразу й збережіть її у менеджері паролів."
  ssh-keygen -t ed25519 -a 64 -f "$SSH_KEY" -C "family-shopping-oracle"
fi
say "Публічний ключ для вставки в Oracle:"
cat "$SSH_KEY.pub"
note "Приватний ключ лишається тільки на цьому комп'ютері: $SSH_KEY"
pause "Коли готові додати публічний ключ у форму Oracle, натисніть Enter."

stage "Безкоштовна ARM VM"
open_url "https://cloud.oracle.com/compute/instances"
step "Compute → Instances → Create instance, у своєму Home Region."
step "Image: Ubuntu 24.04 ARM64 (Always Free Eligible). Shape: VM.Standard.A1.Flex (Always Free Eligible)."
step "Задайте 2 OCPU та 4 GB RAM; boot volume 50 GB. Переконайтеся, що форма показує Always Free Eligible."
step "Fault domain залиште автоматичним. Якщо Oracle пише Out of capacity в AD-1, спробуйте інший Availability Domain, якщо він є."
step "Якщо доступний лише AD-1, спробуйте 1 OCPU та 4 GB RAM. Голос працюватиме повільніше; ми виміряємо це після запуску."
step "Networking: public subnet і public IPv4. Для SSH вставте публічний ключ із попереднього кроку."
step "Створіть VM, дочекайтеся стану Running і скопіюйте Public IP address зі сторінки інстансу."
ask ORACLE_PUBLIC_IP "Публічна IP-адреса VM:"
if [[ ! "$ORACLE_PUBLIC_IP" =~ ^[0-9a-fA-F:.]+$ ]]; then
  warn "IP-адреса має містити лише цифри, літери IPv6, крапки або двокрапки."
  exit 1
fi
write_env ORACLE_PUBLIC_IP "$ORACLE_PUBLIC_IP"
write_env ORACLE_SSH_KEY "$SSH_KEY"
chmod 600 "$ENV_FILE"

stage "Перевірка SSH"
step "Підключаємось до VM як користувач ubuntu та перевіряємо ARM64."
if ssh -o ConnectTimeout=15 -i "$SSH_KEY" "ubuntu@$ORACLE_PUBLIC_IP" uname -m; then
  say "SSH працює."
else
  warn "SSH поки недоступний. Перевірте статус VM, публічну IP-адресу і правило порту 22 у мережі Oracle."
  exit 1
fi

stage "Ключ доступу сервера до GitHub"
ssh -i "$SSH_KEY" "ubuntu@$ORACLE_PUBLIC_IP" \
  'test -f ~/.ssh/family-shopping-deploy || ssh-keygen -q -t ed25519 -N "" -f ~/.ssh/family-shopping-deploy -C family-shopping-deploy'
say "Публічний deploy key (скопіюйте весь рядок):"
ssh -i "$SSH_KEY" "ubuntu@$ORACLE_PUBLIC_IP" 'cat ~/.ssh/family-shopping-deploy.pub'
open_url "https://github.com/zhenikk/family-shopping-bot/settings/keys"
step "Натисніть Add deploy key; назва: Oracle shopping bot. Вставте публічний ключ із цього кроку."
step "Залиште Allow write access вимкненим: серверу потрібне лише читання репозиторію."
pause "Після збереження ключа натисніть Enter."

stage "Токен Telegram і сімейний код"
open_url "https://t.me/BotFather"
step "У чаті @BotFather виконайте /newbot, задайте ім'я й username бота, скопіюйте HTTP API token."
ENV_FILE=.env
ask_secret TELEGRAM_BOT_TOKEN "Вставте токен (ввід прихований):"
if [[ ! "$TELEGRAM_BOT_TOKEN" =~ ^[0-9]+:[A-Za-z0-9_-]+$ ]]; then
  warn "Формат токена не схожий на BotFather HTTP API token."
  exit 1
fi
write_env TELEGRAM_BOT_TOKEN "$TELEGRAM_BOT_TOKEN"
SHOPPING_INVITE_CODE=$(_existing SHOPPING_INVITE_CODE || true)
if [[ -z "$SHOPPING_INVITE_CODE" ]]; then
  SHOPPING_INVITE_CODE=$(python3 -c 'import secrets; print(secrets.token_urlsafe(24))')
fi
write_env SHOPPING_INVITE_CODE "$SHOPPING_INVITE_CODE"
chmod 600 "$ENV_FILE"
say "Секрети збережено лише в локальному .env; файл не потрапляє в Git."
say "Код /join для вас і дружини: $SHOPPING_INVITE_CODE"
say "Передайте асистенту IP-адресу VM. Токен, код і приватний SSH-ключ не надсилайте."

WRITTEN_ENV=(TELEGRAM_BOT_TOKEN SHOPPING_INVITE_CODE)
finish
note "IP-адреса й шлях до SSH-ключа збережені в .oracle-setup.env."
